name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Initialize database
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python - <<'PY'
          from backend.app.db import init_db
          init_db()
          print("Database initialized successfully.")
          PY

      - name: Run tests
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests -q

      - name: Mock review smoke test
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python - <<'PY'
          from backend.app.review_engine import run_review
          from backend.app.llm_client import OllamaClient
          diff = "diff --git a/foo b/foo\n@@ -1 +1 @@\n-foo\n+bar\n"
          client = OllamaClient(mock=True)
          res = run_review(diff, "mentor", client)
          print(f"Mock review items: {len(res)}")
          assert len(res) > 0
          PY
    
      - name: Lint
        run: |
          source .venv/bin/activate
          pip install flake8
          flake8 backend cli
